baseURL: "https://idsintehittapa.github.io"
languageCode: "en-us"

theme: "hugo-creative-portfolio-theme"

rssLimit: 10  # Maximum number of items in the RSS feed.

title: "Data I Guess"

# Enable comments by entering your Disqus shortname
disqusShortname: ""
# Enable Google Analytics by entering your tracking code
googleAnalytics: "UA-142044338-2"

params:
    # Style options: default (pink), blue, green, pink, red, sea, violet
    # Use custom.css for your custom styling
    style: "default"
    description: "Describe your website"
    copyright: "&copy;2019 Johanna Blom"
    sidebarAbout: [
        "Data-I-Guess is my personal project where I explore, analyze, and visualize open access data. I visualize data that I find funny| interetsting| disturbing (usually related to weird things people do since I am into sociology) and while doing so I get better at coding. I use mostly Python but sometimes R.",   
    ]

    email: "jblom15@gmail.com"

    social:
        # facebook     : "full page or profile url in facebook"
        # googleplus   : "full profile url in googleplus"
        email        : "jblom15@gmail"
        twitter      : "https://twitter.com/idsintehittapa"
        linkedin     : "https://www.linkedin.com/in/johanna-blom-2419a181"
        # stackoverflow: "full profile url in stackoverflow"
        #instagram    : "full profile url in instagram"
        github       : "ihttps://github.com/idsintehittapa"
        # youtube      : "full profile url in youtube"
        # whatsapp     : "wa.me service link"


    navlinks:
        - name: "home"
          url: "posts/"
          home: true
        - name: "about"
          url: "about/"
        - name: "contact"
          url: "contact/"
        - name: "tags"
          url: "tags/"

    dateform       : "Jan 2, 2006"
    dateformShort  : "Jan 2"
    dateformNum    : "2006-01-02"
    dateformNumTime: "2006-01-02 15:04 -0700"

taxonomies:
    tag: tags

permalinks:
    posts: /:year/:month/:day/:title/

